### ISSUE TITLE
Firefox loops trying to access https://detectportal.firefox.com/success.txt

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zap-hud#328]
This results in a stream of errors like:
```
187591 [ZAP-ProxyThread-442] DEBUG org.zaproxy.zap.extension.hud.HttpUpgradeProxyListener  - onHttpRequestSend returning a 302 to https://detectportal.firefox.com/success.txt
187591 [ZAP-ProxyThread-7888] DEBUG org.parosproxy.paros.core.proxy.ProxyThread  - IOException: 
java.io.IOException: Error while establishing SSL connection for 'detectportal.firefox.com'!
	at org.parosproxy.paros.core.proxy.ProxyThread.beginSSL(ProxyThread.java:233)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:299)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1761)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1152)
	at sun.security.ssl.ServerHandshaker.sendChangeCipherAndFinish(ServerHandshaker.java:1853)
	at sun.security.ssl.ServerHandshaker.clientFinished(ServerHandshaker.java:1811)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:317)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.parosproxy.paros.network.SSLConnector.createTunnelServerSocket(SSLConnector.java:544)
	at org.parosproxy.paros.core.proxy.ProxyThread.beginSSL(ProxyThread.java:222)
	... 2 more
```

I've got a feeling these checks can be turned off via prefs - maybe we should be doing this for Browser Launch?

**Comment by thc202** [comment]
Will reinstate that (it's currently applying just to AJAX Spider launched browsers, zaproxy/zap-extensions#1848).

**Comment by psiinon** [comment]
Cool - I think its something we should always turn off when launching browsers from ZAP, unless anyone can think of a reason why it should be a (default off) pref?

**Comment by thc202** [comment]
Opened a PR (zaproxy/zap-extensions#1901) to reinstate that now since that's the behaviour of the current version in the marketplace. Happy to move to an option if needed.
