### ISSUE TITLE
HUD components don't load on Chrome

### ISSUE THREAD

**Issue by CollegiateComputer** [zaproxy/zap-hud#454]
Running ZAP Weekly - cross platform version D-2019-03-11 on two Linux machines. Both running Ubuntu 18.04.2 LTS, but one uses GNOME desktop environment and the other is using KDE. Both running the same versions of java (openjdk 10.0.2 2018-07-17). On the KDE machine, the HUD seems to function fine in Firefox and Chrome, but the HUD elements only fully load on Firefox on the GNOME machine. In Chrome on the HUD loads as shown in the screenshot below:
![ZAP-HUD-Chrome](https://user-images.githubusercontent.com/30660159/54324073-7763f900-45d2-11e9-9918-bfebbffca6a7.png)
**Log doesn't show any errors or exceptions until attempting to reset configurations to default in the HUD settings menu, at which point the following exception is logged:**
```
291485 [ZAP-ProxyThread-2] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Socket timeout while reading first message.
297261 [ZAP-ProxyThread-8] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Socket timeout while reading first message.
355136 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:907)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4291)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4148)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4425)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:247)
	at org.zaproxy.zap.utils.PagingTableModel.setData(PagingTableModel.java:339)
	at org.zaproxy.zap.utils.PagingTableModel.access$100(PagingTableModel.java:59)
	at org.zaproxy.zap.utils.PagingTableModel$SegmentLoaderThread$1.run(PagingTableModel.java:432)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
374677 [ZAP-ProxyThread-62] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Timeout reading (client) message after CONNECT to example.com:443
```
The HUD remains the same after this. Not sure if this is a ZAP issue or HUD specific bug. Even though the HUD does fully load in Firefox, it does not seem to be fully functional. Buttons like the break do not seem to trigger any breaking, but instead all requests continue to load normally without a prompt to step, continue, or drop. There may be other issues, but after noticing this feature wasn't functioning I assumed there was a larger issue at play.

**Comment by CollegiateComputer** [comment]
Noticed that the following error is generated when attempting to turn break on from HUD:
```
40659 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsUpdated(DefaultRowSorter.java:907)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4291)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4148)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4425)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:247)
	at org.zaproxy.zap.utils.PagingTableModel.setData(PagingTableModel.java:339)
	at org.zaproxy.zap.utils.PagingTableModel.access$100(PagingTableModel.java:59)
	at org.zaproxy.zap.utils.PagingTableModel$SegmentLoaderThread$1.run(PagingTableModel.java:432)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by psiinon** [comment]
@CollegiateComputer thanks for reporting this.
The IndexOutOfBoundsExcepption's are actually related to the ZAP desktop not the HUD, so I dont think they are related to this.
Can you look in the browser console to see if any errors are logged there?

**Comment by psiinon** [comment]
Oh, and which version(s) of chrome are you using?

**Comment by CollegiateComputer** [comment]
Both machines are running the same version of Chrome: **Version 73.0.3683.75 (Official Build) (64-bit)**
Below are the errors logged to the browser console when visiting a page with the HUD enabled:
```
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://zap//zapCallBackUrl/4018094637011136693?name=tools/commonAlerts.js' failed to load.
	 Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https:    https://zap//zapCallBackUrl/4018094637011136693?name=tools/commonAlerts.js' failed to load undefined:undefined
	     at https:    https://zap//zapCallBackUrl/4018094637011136693?name=serviceworker.js 68:
	         at Array.forEach (<anonymous>:undefined undefined:undefined: {"stack":"Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://zap//zapCallBackUrl/4018094637011136693?name=tools/commonAlerts.js' failed to load.\n    at https://zap//zapCallBackUrl/4018094637011136693?name=serviceworker.js:68:4\n    at Array.forEach (<anonymous>)\n    at https://zap//zapCallBackUrl/4018094637011136693?name=serviceworker.js:67:15"}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693:634 [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"

found in

---> <HudButtons>
       <Root>
warn @ 4018094637011136693:634
4018094637011136693:1896 TypeError: Cannot read property 'name' of null
    at eval (eval at createFunction (4018094637011136693:11596), <anonymous>:3:170)
    at Proxy.renderList (4018094637011136693:2631)
    at Proxy.eval (eval at createFunction (4018094637011136693:11596), <anonymous>:3:111)
    at VueComponent.Vue._render (4018094637011136693:3538)
    at VueComponent.updateComponent (4018094637011136693:4042)
    at Watcher.get (4018094637011136693:4443)
    at Watcher.run (4018094637011136693:4518)
    at flushSchedulerQueue (4018094637011136693:4276)
    at Array.<anonymous> (4018094637011136693:1988)
    at flushCallbacks (4018094637011136693:1914)
logError @ 4018094637011136693:1896
4018094637011136693:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined
	     at https:    https://zap//zapCallBackUrl/4018094637011136693?name=panel.js 171:1
	         at Array.forEach (<anonymous>:undefined undefined:undefined: {}
log @ 4018094637011136693:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'messages' of null
	     TypeError: Cannot read property 'messages' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693?name=utils.js:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'messages' of null
	     TypeError: Cannot read property 'messages' of nul undefined:undefined: {}
log @ 4018094637011136693?name=utils.js:708
4018094637011136693:634 [Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"

found in

---> <HudButtons>
       <Root>
warn @ 4018094637011136693:634
4018094637011136693:1896 TypeError: Cannot read property 'name' of null
    at eval (eval at createFunction (4018094637011136693:11596), <anonymous>:3:170)
    at Proxy.renderList (4018094637011136693:2631)
    at Proxy.eval (eval at createFunction (4018094637011136693:11596), <anonymous>:3:111)
    at VueComponent.Vue._render (4018094637011136693:3538)
    at VueComponent.updateComponent (4018094637011136693:4042)
    at Watcher.get (4018094637011136693:4443)
    at Watcher.run (4018094637011136693:4518)
    at flushSchedulerQueue (4018094637011136693:4276)
    at Array.<anonymous> (4018094637011136693:1988)
    at flushCallbacks (4018094637011136693:1914)
logError @ 4018094637011136693:1896
4018094637011136693:708 23:44:03 GMT-0400 (Eastern Daylight Time) ERROR errorHandler: TypeError: Cannot read property 'name' of null
	     TypeError: Cannot read property 'name' of nul undefined:undefined
	     at https:    https://zap//zapCallBackUrl/4018094637011136693?name=panel.js 171:1
	         at Array.forEach (<anonymous>:undefined undefined:undefined: {}
log @ 4018094637011136693:708
```

**Comment by dscrobonia** [comment]
@psiinon are we moving forward with this issue? Don't want to let it sit on the burners for too long. :)

**Comment by psiinon** [comment]
@dscrobonia agreed, but tbh I have no idea whats going on here :/
Can anyone else reproduce this?
Any suggestions as to what could be going wrong?
I think its likely to be a HUD issue rather than a core ZAP one.

**Comment by psiinon** [comment]
This looks like the issue that prevents the tests from running consistantly.
I've also found a way to reproduce it more consistantly - this always seems to happen for me is ZAP is under load, eg spidering or active scanning.
That implies its a timing issue thats just more visible when ZAP is doing something else.

**Comment by psiinon** [comment]
If the HUD gets in this state then it looks like it can be fixed by removing the service worker and refreshing the target page, assuming ZAP is no longer under load.
